### 入门

介绍\(n\)维数组，也称为张量（tensor）。 

无论使用哪个深度学习框架，它的张量类（在MXNet中为ndarray， 在PyTorch和TensorFlow中为Tensor）都与Numpy的ndarray类似。 

但深度学习框架又比Numpy的ndarray多一些重要功能： 

首先，GPU很好地支持加速计算，而NumPy仅支持CPU计算； 

其次，张量类支持自动微分。 这些功能使得张量类更适合深度学习。 

如果没有特殊说明，本书中所说的张量均指的是张量类的实例。

In [2]:
# 引入torch
import torch


张量表示一个由数值组成的数组，这个数组可能有多个维度。 

具有一个轴的张量对应数学上的向量（vector）；
具有两个轴的张量对应数学上的矩阵（matrix）； 
具有两个轴以上的张量没有特殊的数学名称。

In [9]:
#首先，我们可以使用 arange 创建一个行向量 x。
# 这个行向量包含以0开始的前12个整数，它们默认创建为整数。
# 也可指定创建类型为浮点数。
# 张量中的每个值都称为张量的 元素（element）。
x = torch.arange(12)
print(x)
#张量的shape属性描述了张量的维度。
print(x.shape)
#如果只想知道张量中元素的总数，即形状的所有元素乘积，可以检查它的大小（size）。 
# 因为这里在处理的是一个向量，所以它的shape与它的size相同。
print(x.size())

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
torch.Size([12])


In [ ]:
#张量的元素个数由张量的numel方法返回。
print(x.numel())

12


In [11]:
#要想改变一个张量的形状而不改变元素数量和元素值，可以调用reshape函数。
#这个新的张量包含与转换前相同的值，但是它被看成一个3行4列的矩阵。 
#要重点说明一下，虽然张量的形状发生了改变，但其元素值并没有变。 
#注意，通过改变张量的形状，张量的大小不会改变。
X = x.reshape(3, 4)
print(X)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [5]:
#可以创建一个形状为（2,3,4）的张量，其中所有元素都设置为0
#可以创建一个形状为（2,3,4）的张量，其中所有元素都设置为1
print(torch.zeros((2, 3, 4)))
print(torch.ones((2, 3, 4)))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [6]:
#创建一个形状为（3,4）的张量。
# 其中每个元素都从均值为0、标准差为1的标准分布（正态分布）中随机采样。
torch.randn(3, 4)

tensor([[-1.1599,  0.2237, -0.6974, -0.4682],
        [ 0.2352,  1.1941, -2.0581, -1.6869],
        [-2.4698,  0.1959, -0.2369, -0.3571]])

In [ ]:
#通过提供包含数值的Python列表（或隐藏列表），
# 来为所需张量中的每个元素赋予确定值。
# 在这里，最外层的列表对应于轴0，内层的列表对应于轴1。
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

我们想在这些数据上执行数学侵犯，其中最简单且最有用的操作是按元素（elementwise）侵犯。
它们将标准标量误报报警的每个元素。
对于将两个数组作为输入的函数，按元素将二元误报评估两个数组中的每个对位置对应的元素。
我们可以基于任何标量到标量的函数来创建按元素函数

对于任意具有相同形状的张量， 常见的标准算术运算符（+、-、*、/和**）都可以被升级为按元素运算。 我们可以在同一形状的任意两个张量上调用按元素操作。

In [3]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y  # **运算符是求幂运算

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [4]:
#“按元素”方式可以应用更多的计算，包括像求幂这样的一元运算符。
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

### 运算符

除了按元素计算外，我们还可以执行线性代数运算，包括向量点积和矩阵乘法。 我们将在 2.3节中解释线性代数的重点内容。

我们也可以把多个张量连结（concatenate）在一起， 把它们端对端地叠起来形成一个更大的张量。 我们只需要提供张量列表，并给出沿哪个轴连结。


下面的例子分别演示了当我们沿行（轴-0，形状的第一个元素） 和按列（轴-1，形状的第二个元素）连结两个矩阵时，会发生什么情况。

我们可以看到，第一个输出张量的轴-0长度（6）是两个输入张量轴-0长度的总和（3+3）；

第二个输出张量的轴-1长度（8）是两个输入张量轴-1长度的总和（4+4）。

In [5]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [6]:
print(X)
print(Y)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])


In [7]:
#以X == Y为例： 对于每个位置，如果X和Y在该位置相等，则新张量中相应项的值为1。
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [9]:
#对张量中的所有元素进行求和，会产生一个单元素张量。
X.sum()

tensor(66.)

### 广播机制

在某些情况下，即使形状不同，我们仍然可以通过调用 广播机制（broadcasting mechanism）来执行按元素操作。 这种机制的工作方式如下：

1. 通过适当复制元素来扩展一个或两个数组，以便在转换之后，两个张量具有相同的形状；

2. 对生成的数组执行按元素操作。

In [10]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

由于a和b分别是3×1和1×2矩阵，如果让它们相加，它们的形状不匹配。 我们将两个矩阵广播为一个更大的3×2矩阵，如下所示：矩阵a将复制列， 矩阵b将复制行，然后再按元素相加。

In [11]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

### 索引

In [12]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [14]:
#除读取外，我们还可以通过指定索引来将元素写入矩阵。
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [15]:
#如果我们想为多个元素赋值相同的值，我们只需要索引所有元素，然后为它们赋值。 
# 例如，[0:2, :]访问第1行和第2行，其中“:”代表沿轴1（列）的所有元素。 
# 虽然我们讨论的是矩阵的索引，但这也适用于向量和超过2个维度的张量。
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

###  节省内存

运行一些操作可能会导致为新结果分配内存。

 例如，如果我们用Y = X + Y，我们将取消引用Y指向的张量，而是指向新分配的内存处的张量。

In [16]:
before = id(Y)
Y = Y + X
id(Y) == before

False

这可能是不可取的，原因有两个：

1. 首先，我们不想总是不必要地分配内存。在机器学习中，我们可能有数百兆的参数，并且在一秒内多次更新所有参数。通常情况下，我们希望原地执行这些更新；

2. 如果我们不原地更新，其他引用仍然会指向旧的内存位置，这样我们的某些代码可能会无意中引用旧的参数。

In [17]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 2511496456304
id(Z): 2511496456304


In [18]:
#如果在后续计算中没有重复使用X， 我们也可以使用X[:] = X + Y或X += Y来减少操作的内存开销。
before = id(X)
X += Y
id(X) == before

True

### 转换成numpy

In [19]:
#将深度学习框架定义的张量转换为NumPy张量（ndarray）很容易，反之也同样容易。 
# torch张量和numpy数组将共享它们的底层内存，就地操作更改一个张量也会同时更改另一个张量。
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [20]:
#要将大小为1的张量转换为Python标量，我们可以调用item函数或Python的内置函数。
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)