# 线性代数

标量由只有一个元素的张量表示。 下面的代码将实例化两个标量，并执行一些熟悉的算术运算，即加法、乘法、除法和指数。

In [1]:
import torch

x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x / y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [2]:
#人们通过一维张量表示向量。
# 一般来说，张量可以具有任意长度，取决于机器的内存限制。

x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [3]:
#通过张量的索引来访问任一元素。
x[3]

tensor(3)

In [5]:
#调用Python的内置len()函数来访问张量的长度。
# 当用张量表示一个向量（只有一个轴）时，我们也可以通过.shape属性访问向量的长度
len(x), x.shape

(4, torch.Size([4]))

向量或轴的维度被用来表示向量或轴的长度，即向量或轴的元素数量。 然而，张量的维度用来表示张量具有的轴数。 在这个意义上，张量的某个轴的维数就是这个轴的长度。

In [6]:
## 矩阵
# 矩阵是二维张量。我们可以通过指定行和列来访问矩阵中的任一元素。    
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [7]:
A[1, 2]  # 访问第2行第3列的元素

tensor(6)

In [8]:
# 转置
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [18]:
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B == B.T


tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [19]:
B = B + torch.eye(3)
B

tensor([[2., 2., 3.],
        [2., 1., 4.],
        [3., 4., 6.]])

In [20]:
B.transpose(0, 1) == B

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

# 张量


In [21]:
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

## 张量 的基本性质

In [22]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # 通过分配新内存，将A的一个副本分配给B
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [24]:
#两个矩阵的按元素乘法称为Hadamard积（Hadamard product）
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [25]:
# 将张量乘以或加上一个标量不会改变张量的形状，
# 其中张量的每个元素都将与标量相加或相乘。
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

## 降维

In [27]:
#求和
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [28]:
# 我们可以表示任意形状张量的元素和
print(A)
A.sum(),A.sum(axis=0), A.sum(axis=1),A.shape

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])


(tensor(190.),
 tensor([40., 45., 50., 55.]),
 tensor([ 6., 22., 38., 54., 70.]),
 torch.Size([5, 4]))

默认情况下，调用求和函数会沿所有的轴降低张量的维度，使它变为一个标量。 我们还可以指定张量沿哪一个轴来通过求和降低维度。 

In [ ]:
# 以矩阵为例，为了通过求和所有行的元素来降维（轴0），
# 可以在调用函数时指定axis=0。
# 由于输入矩阵沿0轴降维以生成输出向量，因此输入轴0的维数在输出形状中消失。
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [30]:
#指定axis=1将通过汇总所有列的元素降维（轴1）。
# 因此，输入轴1的维数在输出形状中消失。
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

In [31]:
#沿着行和列对矩阵求和，等价于对矩阵的所有元素进行求和。
A.sum(axis=[0, 1])  # 结果和A.sum()相同

tensor(190.)

In [35]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [34]:
A.numel()

20

In [32]:
#可以调用函数来计算任意形状张量的平均值。
A.mean(), A.sum() / A.numel()

(tensor(9.5000), tensor(9.5000))

In [36]:
#计算平均值的函数也可以沿指定轴降低张量的维度。
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

## 非降维求和

In [38]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [37]:
#调用函数来计算总和或均值时保持轴数
sum_A = A.sum(axis=1, keepdims=True)
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [40]:
#由于sum_A在对每行进行求和后仍保持两个轴，我们可以通过广播将A除以sum_A。
A / sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [41]:
#沿某个轴计算A元素的累积总和， 比如axis=0（按行计算），可以调用cumsum函数。 
# 此函数不会沿任何轴降低输入张量的维度。
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

## 点积

In [42]:
y = torch.ones(4, dtype = torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [43]:
#可以通过执行按元素乘法，然后进行求和来表示两个向量的点积：
torch.sum(x * y)

tensor(6.)

In [45]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [46]:
x

tensor([0., 1., 2., 3.])

In [44]:
#使用张量表示矩阵-向量积，我们使用mv函数。
# 当我们为矩阵A和向量x调用torch.mv(A, x)时，会执行矩阵-向量积。
# 注意，A的列维数（沿轴1的长度）必须与x的维数（其长度）相同。
A.shape, x.shape, torch.mv(A, x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

In [47]:
#我们在A和B上执行矩阵乘法。 
# 这里的A是一个5行4列的矩阵，B是一个4行3列的矩阵。 
# 两者相乘后，我们得到了一个5行3列的矩阵
B = torch.ones(4, 3)
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

In [48]:
B

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [50]:
# 二范数
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [51]:
#将绝对值函数和按元素求和组合起来
torch.abs(u).sum()

tensor(7.)

In [ ]:
#Frobenius范数满足向量范数的所有性质，它就像是矩阵形向量的范数。
# 调用以下函数将计算矩阵的Frobenius范数。(矩阵元素平方和的平方根)
torch.norm(torch.ones((4, 9)))

tensor(6.)

In [53]:
z=torch.ones((4, 9))
z

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

标量、向量、矩阵和张量是线性代数中的基本数学对象。

向量泛化自标量，矩阵泛化自向量。

标量、向量、矩阵和张量分别具有零、一、二和任意数量的轴。

一个张量可以通过sum和mean沿指定的轴降低维度。

两个矩阵的按元素乘法被称为他们的Hadamard积。它与矩阵乘法不同。

在深度学习中，我们经常使用范数，如
范数、
范数和Frobenius范数。

我们可以对标量、向量、矩阵和张量执行各种操作。

In [54]:
#证明一个矩阵A的转置的转置是A
A = torch.arange(20).reshape(5, 4)
A_T_T = A.T.T

In [55]:
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [56]:
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])